# Generated by Django 5.0.1 on 2024-01-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='detail',
            new_name='details',
        ),
    ]
