# Generated by Django 4.2.7 on 2024-01-19 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_gallery_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='gellary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.gallery'),
        ),
    ]
