# Generated by Django 5.0.1 on 2024-01-20 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_galleryimage_gellary'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.IntegerField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SubcripPlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subcripplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subcripplan')),
            ],
        ),
    ]
