# Generated by Django 5.0.1 on 2024-01-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_subcripplan_subcripplanfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcripplan',
            name='price',
            field=models.IntegerField(),
        ),
    ]
