# Generated by Django 5.0.1 on 2024-01-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_subcripplan_highlight_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcripplanfeature',
            name='subcripplan',
        ),
        migrations.AddField(
            model_name='subcripplanfeature',
            name='subcripplan',
            field=models.ManyToManyField(to='app.subcripplan'),
        ),
    ]
