# Generated by Django 5.0.1 on 2024-01-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_subcripplanfeature_subcripplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcripplan',
            name='max_member',
            field=models.IntegerField(null=True),
        ),
    ]
