# Generated by Django 5.0.1 on 2024-01-22 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_subcripplan_max_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_month', models.IntegerField()),
                ('total_discount', models.IntegerField()),
                ('subcripplan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subcripplan')),
            ],
        ),
    ]
