# Generated by Django 5.0.1 on 2024-01-24 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_trainer_pwd_trainer_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='pwd',
            new_name='password',
        ),
    ]
