# Generated by Django 5.0.1 on 2024-01-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_notify_readby_trainer_alter_notify_readby_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
