# Generated by Django 5.0.1 on 2024-01-24 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_notify_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.subscriber')),
                ('trainer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.trainer')),
            ],
        ),
    ]
