# Generated by Django 5.0.1 on 2024-01-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_subcripplan_validate_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='regis_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
