# Generated by Django 5.0.1 on 2024-01-30 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_banners_options_trainerachivements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainerachivements',
            options={'verbose_name_plural': 'TrainerAchivements'},
        ),
    ]
