# Generated by Django 5.0.1 on 2024-01-31 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_trainersalary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainersalary',
            options={'verbose_name_plural': 'Trainersalary'},
        ),
    ]
